# Generated by Django 4.2.6 on 2023-10-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_user_name'),
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='blog.user'),
            preserve_default=False,
        ),
    ]
