# Generated by Django 4.2.6 on 2023-10-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_skills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
    ]
