# Generated by Django 4.2.6 on 2023-10-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_user_name'),
        ('programming', '0003_remove_skills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='blog.user'),
        ),
    ]
