# Generated by Django 4.2.6 on 2023-10-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_alter_technology_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technology',
            table='technology',
        ),
    ]
