# Generated by Django 4.2.6 on 2023-10-31 09:55

import blog.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_alter_technology_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=1, upload_to=blog.models.base_model.PathAndRename('blog/blogobj/images/')),
            preserve_default=False,
        ),
    ]
