version: '3.3'

services:
  app:
    restart: always
    container_name: django
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - blogdb
    env_file:
      - .env
    volumes:
      - .:/app
  blogdb:
    restart: always
    image: postgres:latest
    container_name: blogdb
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    volumes:
      - ./data:/var/lib/postgresql/data


  init_db:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate --noinput
    depends_on:
      - blogdb
