# Generated by Django 4.2.6 on 2023-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
