# Generated by Django 4.2.6 on 2023-10-06 05:56

import blog.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.base_model.PathAndRename('blog/userobj/images/')),
        ),
    ]
