# Generated by Django 4.2.6 on 2023-10-06 10:57

import blog.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to=blog.models.base_model.PathAndRename('blog/blogobj/images/')),
            preserve_default=False,
        ),
    ]
