# Generated by Django 4.2.6 on 2023-10-06 13:21

import blog.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_currentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[blog.models.user.check_phone]),
        ),
    ]
