# Generated by Django 4.2.6 on 2023-10-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_visitor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitor',
            table='visitor',
        ),
    ]
