# Generated by Django 4.2.6 on 2023-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_visitor_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='referring_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
