# Generated by Django 4.2.6 on 2023-10-06 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
        ('about', '0003_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network', to='blog.user')),
            ],
            options={
                'db_table': 'social_network',
            },
        ),
    ]
