# Generated by Django 4.2.6 on 2023-10-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact_ip_address_contact_user'),
    ]

    operations = [
    ]
