# Generated by Django 4.2.6 on 2023-10-06 15:14

import about.models.icon
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[about.models.icon.icon_name_case_check]),
        ),
    ]
