# Generated by Django 4.2.6 on 2023-10-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
