# Generated by Django 4.2.6 on 2023-10-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_contact_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
