# Generated by Django 4.2.6 on 2023-10-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_contact1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
