name: Run tests
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt

  depoy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: back.javthon.uz
          username: root
          key: ${{ secrets.KEY }}
          scripts: |
            cd blog
            git pull
            systemctl daemon-reload
            systemctl restart gunicorn.socket gunicorn.service
            systemctl restart nginx


#      - name: Execute tests
#        env:
#          DJANGO_SETTINGS_MODULE: config.settings
#        run: python3 manage.py test