name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    services:
      postgres:
        image: postgres:14.9
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt

  depoy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          branch: 'main'
          sha: '${{ github.event.pull_request.head.sha }}'
          host: back.javthon.uz
          username: root
          key: ${{ secrets.KEY }}
          scripts: |
            cd blog
            git pull origi main
            systemctl daemon-reload
            systemctl restart gunicorn.socket gunicorn.service
            systemctl restart nginx
